/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.CControl_admin;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Interfaz_Admin1 extends javax.swing.JFrame {

    CControl_admin control = new CControl_admin();

    /**
     * Creates new form Intrefaz
     */
    public Interfaz_Admin1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Panel_Clientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Clientes = new javax.swing.JTable();
        L_ID = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        L_Nombre = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        L_Cuenta = new javax.swing.JLabel();
        Cuenta = new javax.swing.JTextField();
        L_Apellido = new javax.swing.JLabel();
        Apellido = new javax.swing.JTextField();
        L_Telefono = new javax.swing.JLabel();
        Telefono = new javax.swing.JTextField();
        L_Ciudad = new javax.swing.JLabel();
        Ciudad = new javax.swing.JTextField();
        L_Saldo = new javax.swing.JLabel();
        Saldo = new javax.swing.JTextField();
        Agregar = new javax.swing.JButton();
        Editar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Listar = new javax.swing.JButton();
        Buscar_Nombre = new javax.swing.JButton();
        Buscar_ID = new javax.swing.JButton();
        L_Monto = new javax.swing.JLabel();
        Monto = new javax.swing.JTextField();
        Consignar = new javax.swing.JButton();
        Retirar = new javax.swing.JButton();
        Panel_Cajeros = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCajeros = new javax.swing.JTable();
        L_ID_Caje = new javax.swing.JLabel();
        ID_Caje = new javax.swing.JTextField();
        L_N_10 = new javax.swing.JLabel();
        N_10 = new javax.swing.JTextField();
        L_N_20 = new javax.swing.JLabel();
        N_20 = new javax.swing.JTextField();
        L_N_50 = new javax.swing.JLabel();
        N_50 = new javax.swing.JTextField();
        L_N_100 = new javax.swing.JLabel();
        N_100 = new javax.swing.JTextField();
        Agregar_Caje = new javax.swing.JButton();
        Editar_Caje = new javax.swing.JButton();
        Eliminar_Caje = new javax.swing.JButton();
        Listar_Caje = new javax.swing.JButton();
        Buscar_Caje = new javax.swing.JButton();
        Agregar_Bill = new javax.swing.JButton();
        Quitar_Bill = new javax.swing.JButton();
        Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tabla_Clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido", "Telefono", "Ciudad", "# de cuenta", "Saldo", "Estado"
            }
        ));
        jScrollPane1.setViewportView(Tabla_Clientes);

        L_ID.setText("ID : ");

        L_Nombre.setText("Nombre : ");

        L_Cuenta.setText("# de Cuenta : ");

        L_Apellido.setText("Apellido : ");

        L_Telefono.setText("Telefono : ");

        L_Ciudad.setText("Ciudad : ");

        L_Saldo.setText("Saldo : ");

        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Listar.setText("Listar");
        Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarActionPerformed(evt);
            }
        });

        Buscar_Nombre.setText("Buscar por nombre");
        Buscar_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar_NombreActionPerformed(evt);
            }
        });

        Buscar_ID.setText("Buscar por ID");
        Buscar_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar_IDActionPerformed(evt);
            }
        });

        L_Monto.setText("Monto : ");

        Consignar.setText("Consignar");
        Consignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsignarActionPerformed(evt);
            }
        });

        Retirar.setText("Retirar");
        Retirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetirarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_ClientesLayout = new javax.swing.GroupLayout(Panel_Clientes);
        Panel_Clientes.setLayout(Panel_ClientesLayout);
        Panel_ClientesLayout.setHorizontalGroup(
            Panel_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Panel_ClientesLayout.createSequentialGroup()
                        .addComponent(L_Cuenta)
                        .addGap(18, 18, 18)
                        .addComponent(Cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(L_Saldo)
                        .addGap(18, 18, 18)
                        .addComponent(Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Panel_ClientesLayout.createSequentialGroup()
                        .addGroup(Panel_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_ClientesLayout.createSequentialGroup()
                                .addComponent(L_ID)
                                .addGap(18, 18, 18)
                                .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(L_Nombre)
                                .addGap(18, 18, 18)
                                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(L_Apellido)
                                .addGap(18, 18, 18)
                                .addComponent(Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(L_Telefono)
                                .addGap(18, 18, 18)
                                .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(L_Ciudad)
                                .addGap(18, 18, 18)
                                .addComponent(Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Panel_ClientesLayout.createSequentialGroup()
                                .addComponent(Agregar)
                                .addGap(18, 18, 18)
                                .addComponent(Editar)
                                .addGap(18, 18, 18)
                                .addComponent(Eliminar)
                                .addGap(18, 18, 18)
                                .addComponent(Listar)
                                .addGap(18, 18, 18)
                                .addComponent(Buscar_Nombre)
                                .addGap(18, 18, 18)
                                .addComponent(Buscar_ID)))
                        .addGap(0, 172, Short.MAX_VALUE))))
            .addGroup(Panel_ClientesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(L_Monto)
                .addGap(18, 18, 18)
                .addComponent(Monto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Consignar)
                .addGap(18, 18, 18)
                .addComponent(Retirar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Panel_ClientesLayout.setVerticalGroup(
            Panel_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ClientesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Panel_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_Nombre)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_Apellido)
                    .addComponent(Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_Telefono)
                    .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_Ciudad)
                    .addComponent(Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_Cuenta)
                    .addComponent(Cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_Saldo)
                    .addComponent(Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addGroup(Panel_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Agregar)
                    .addComponent(Editar)
                    .addComponent(Eliminar)
                    .addComponent(Listar)
                    .addComponent(Buscar_Nombre)
                    .addComponent(Buscar_ID))
                .addGap(81, 81, 81)
                .addGroup(Panel_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_Monto)
                    .addComponent(Monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Consignar)
                    .addComponent(Retirar))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Clientes", Panel_Clientes);

        tablaCajeros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NDiez", "NVeinte", "NCincuenta", "NCien", "Estado"
            }
        ));
        jScrollPane2.setViewportView(tablaCajeros);

        L_ID_Caje.setText("ID  : ");

        L_N_10.setText("$10.000 : ");

        L_N_20.setText("$20.000 : ");

        L_N_50.setText("$50.000 : ");

        L_N_100.setText("$100.000 : ");

        Agregar_Caje.setText("Agregar");
        Agregar_Caje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_CajeActionPerformed(evt);
            }
        });

        Editar_Caje.setText("Editar");
        Editar_Caje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Editar_CajeActionPerformed(evt);
            }
        });

        Eliminar_Caje.setText("Eliminar");
        Eliminar_Caje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_CajeActionPerformed(evt);
            }
        });

        Listar_Caje.setText("Listar");
        Listar_Caje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listar_CajeActionPerformed(evt);
            }
        });

        Buscar_Caje.setText("Buscar");
        Buscar_Caje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar_CajeActionPerformed(evt);
            }
        });

        Agregar_Bill.setText("Agregar Billetes");
        Agregar_Bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_BillActionPerformed(evt);
            }
        });

        Quitar_Bill.setText("Quitar Billetes");
        Quitar_Bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Quitar_BillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_CajerosLayout = new javax.swing.GroupLayout(Panel_Cajeros);
        Panel_Cajeros.setLayout(Panel_CajerosLayout);
        Panel_CajerosLayout.setHorizontalGroup(
            Panel_CajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_CajerosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_CajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(Panel_CajerosLayout.createSequentialGroup()
                        .addComponent(L_ID_Caje)
                        .addGap(18, 18, 18)
                        .addComponent(ID_Caje, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(L_N_10)
                        .addGap(18, 18, 18)
                        .addGroup(Panel_CajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_CajerosLayout.createSequentialGroup()
                                .addComponent(Agregar_Caje)
                                .addGap(18, 18, 18)
                                .addComponent(Editar_Caje)
                                .addGap(18, 18, 18)
                                .addComponent(Eliminar_Caje)
                                .addGap(18, 18, 18)
                                .addComponent(Listar_Caje)
                                .addGap(18, 18, 18)
                                .addComponent(Buscar_Caje))
                            .addGroup(Panel_CajerosLayout.createSequentialGroup()
                                .addComponent(N_10, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(L_N_20)
                                .addGap(18, 18, 18)
                                .addComponent(N_20, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(L_N_50)
                                .addGap(18, 18, 18)
                                .addComponent(N_50, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(L_N_100)
                                .addGap(18, 18, 18)
                                .addComponent(N_100, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 180, Short.MAX_VALUE))))
            .addGroup(Panel_CajerosLayout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(Agregar_Bill)
                .addGap(18, 18, 18)
                .addComponent(Quitar_Bill)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Panel_CajerosLayout.setVerticalGroup(
            Panel_CajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_CajerosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Panel_CajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_ID_Caje)
                    .addComponent(ID_Caje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_N_10)
                    .addComponent(N_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_N_20)
                    .addComponent(N_20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_N_50)
                    .addComponent(N_50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_N_100)
                    .addComponent(N_100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(Panel_CajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Agregar_Caje)
                    .addComponent(Editar_Caje)
                    .addComponent(Eliminar_Caje)
                    .addComponent(Listar_Caje)
                    .addComponent(Buscar_Caje))
                .addGap(18, 18, 18)
                .addGroup(Panel_CajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Agregar_Bill)
                    .addComponent(Quitar_Bill))
                .addContainerGap(262, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cajeros", Panel_Cajeros);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Salir)
                .addGap(420, 420, 420))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        try {
            String nombre = Nombre.getText();
            String apellido = Apellido.getText();
            String telefono = Telefono.getText();
            String ciudad = Ciudad.getText();
            String cuenta = Cuenta.getText();
            double saldo = Double.parseDouble(Saldo.getText());

            control.agregarCliente(nombre, apellido, telefono, ciudad, cuenta, saldo);
            control.listarClientes(Tabla_Clientes); // refrescar tabla
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al agregar: " + e.getMessage());
        }
    }//GEN-LAST:event_AgregarActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        try {
            int id = Integer.parseInt(ID.getText());
            String nombre = Nombre.getText();
            String apellido = Apellido.getText();
            String telefono = Telefono.getText();
            String ciudad = Ciudad.getText();
            String cuenta = Cuenta.getText();
            double saldo = Double.parseDouble(Saldo.getText());

            control.editarCliente(id, nombre, apellido, telefono, ciudad, cuenta, saldo);
            control.listarClientes(Tabla_Clientes);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al editar: " + e.getMessage());
        }
    }//GEN-LAST:event_EditarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        try {
            int id = Integer.parseInt(ID.getText());
            control.eliminarCliente(id);
            control.listarClientes(Tabla_Clientes);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarActionPerformed
        control.listarClientes(Tabla_Clientes);
    }//GEN-LAST:event_ListarActionPerformed

    private void Buscar_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar_NombreActionPerformed
        String nombre = Nombre.getText().trim();
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un nombre para buscar.");
            return;
        }
        control.buscarClientePorNombre(Tabla_Clientes, nombre);
    }//GEN-LAST:event_Buscar_NombreActionPerformed

    private void Buscar_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar_IDActionPerformed
        try {
            int id = Integer.parseInt(ID.getText().trim());
            control.buscarClientePorId(Tabla_Clientes, id);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un ID válido.");
        }
    }//GEN-LAST:event_Buscar_IDActionPerformed

    private void ConsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsignarActionPerformed
        try {
            int id = Integer.parseInt(ID.getText());
            double monto = Double.parseDouble(Monto.getText());
            control.consignar(id, monto);
            control.listarClientes(Tabla_Clientes);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al consignar: " + e.getMessage());
        }
    }//GEN-LAST:event_ConsignarActionPerformed

    private void RetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetirarActionPerformed
        try {
            int id = Integer.parseInt(ID.getText());
            double monto = Double.parseDouble(Monto.getText());
            control.retirar(id, monto);
            control.listarClientes(Tabla_Clientes);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al retirar: " + e.getMessage());
        }
    }//GEN-LAST:event_RetirarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        new Interfaz().setVisible(true);
        dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void Agregar_CajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_CajeActionPerformed
        try {
            int n10 = Integer.parseInt(N_10.getText());
            int n20 = Integer.parseInt(N_20.getText());
            int n50 = Integer.parseInt(N_50.getText());
            int n100 = Integer.parseInt(N_100.getText());

            control.agregarCajero(n10, n20, n50, n100);
            control.listarCajeros(tablaCajeros);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingresa solo números válidos en los campos de billetes.");
        }
    }//GEN-LAST:event_Agregar_CajeActionPerformed

    private void Editar_CajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Editar_CajeActionPerformed
        try {
            int id = Integer.parseInt(ID_Caje.getText());
            int n10 = Integer.parseInt(N_10.getText());
            int n20 = Integer.parseInt(N_20.getText());
            int n50 = Integer.parseInt(N_50.getText());
            int n100 = Integer.parseInt(N_100.getText());

            control.editarCajero(id, n10, n20, n50, n100);
            control.listarCajeros(tablaCajeros);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: verifica que todos los campos estén llenos con números.");
        }
    }//GEN-LAST:event_Editar_CajeActionPerformed

    private void Eliminar_CajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_CajeActionPerformed
        try {
            int id = Integer.parseInt(ID_Caje.getText());
            control.eliminarCajero(id);
            control.listarCajeros(tablaCajeros);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un ID de cajero válido.");
        }
    }//GEN-LAST:event_Eliminar_CajeActionPerformed

    private void Listar_CajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Listar_CajeActionPerformed
        control.listarCajeros(tablaCajeros);
    }//GEN-LAST:event_Listar_CajeActionPerformed

    private void Buscar_CajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar_CajeActionPerformed
        try {
            int id = Integer.parseInt(ID_Caje.getText());
            control.buscarCajero(tablaCajeros, id);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un ID válido para buscar.");
        }
    }//GEN-LAST:event_Buscar_CajeActionPerformed

    private void Agregar_BillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_BillActionPerformed
        try {
            int id = Integer.parseInt(ID_Caje.getText());
            int n10 = Integer.parseInt(N_10.getText());
            int n20 = Integer.parseInt(N_20.getText());
            int n50 = Integer.parseInt(N_50.getText());
            int n100 = Integer.parseInt(N_100.getText());

            control.agregarBilletes(id, n10, n20, n50, n100);
            control.listarCajeros(tablaCajeros);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: ingresa números válidos en los campos de billetes.");
        }
    }//GEN-LAST:event_Agregar_BillActionPerformed

    private void Quitar_BillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Quitar_BillActionPerformed
        try {
            int id = Integer.parseInt(ID_Caje.getText());
            int n10 = Integer.parseInt(N_10.getText());
            int n20 = Integer.parseInt(N_20.getText());
            int n50 = Integer.parseInt(N_50.getText());
            int n100 = Integer.parseInt(N_100.getText());

            control.quitarBilletes(id, n10, n20, n50, n100);
            control.listarCajeros(tablaCajeros);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: ingresa números válidos en los campos de billetes.");
        }
    }//GEN-LAST:event_Quitar_BillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Admin1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Agregar_Bill;
    private javax.swing.JButton Agregar_Caje;
    private javax.swing.JTextField Apellido;
    private javax.swing.JButton Buscar_Caje;
    private javax.swing.JButton Buscar_ID;
    private javax.swing.JButton Buscar_Nombre;
    private javax.swing.JTextField Ciudad;
    private javax.swing.JButton Consignar;
    private javax.swing.JTextField Cuenta;
    private javax.swing.JButton Editar;
    private javax.swing.JButton Editar_Caje;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Eliminar_Caje;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField ID_Caje;
    private javax.swing.JLabel L_Apellido;
    private javax.swing.JLabel L_Ciudad;
    private javax.swing.JLabel L_Cuenta;
    private javax.swing.JLabel L_ID;
    private javax.swing.JLabel L_ID_Caje;
    private javax.swing.JLabel L_Monto;
    private javax.swing.JLabel L_N_10;
    private javax.swing.JLabel L_N_100;
    private javax.swing.JLabel L_N_20;
    private javax.swing.JLabel L_N_50;
    private javax.swing.JLabel L_Nombre;
    private javax.swing.JLabel L_Saldo;
    private javax.swing.JLabel L_Telefono;
    private javax.swing.JButton Listar;
    private javax.swing.JButton Listar_Caje;
    private javax.swing.JTextField Monto;
    private javax.swing.JTextField N_10;
    private javax.swing.JTextField N_100;
    private javax.swing.JTextField N_20;
    private javax.swing.JTextField N_50;
    private javax.swing.JTextField Nombre;
    private javax.swing.JPanel Panel_Cajeros;
    private javax.swing.JPanel Panel_Clientes;
    private javax.swing.JButton Quitar_Bill;
    private javax.swing.JButton Retirar;
    private javax.swing.JTextField Saldo;
    private javax.swing.JButton Salir;
    public javax.swing.JTable Tabla_Clientes;
    private javax.swing.JTextField Telefono;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaCajeros;
    // End of variables declaration//GEN-END:variables
}
